### PR TITLE
Remove deployment hurdles

### PR DESCRIPTION
**Pull request by ifavo**
The sample project has some issues:

1. The official modules are found in the `@vechain` group
2. The first deployment test shows that multiple installs are required, they are added:
```
$ npx hardhat run scripts/deploy.js
Error HH801: Plugin @nomicfoundation/hardhat-toolbox requires the following dependencies to be installed: @nomicfoundation/hardhat-network-helpers, @nomicfoundation/hardhat-chai-matchers, @nomiclabs/hardhat-ethers, @nomiclabs/hardhat-etherscan, @types/chai, @types/mocha, @typechain/ethers-v5, @typechain/hardhat, chai, hardhat-gas-reporter, solidity-coverage, ts-node, typechain, typescript.
Please run: npm install --save-dev "@nomicfoundation/hardhat-network-helpers@^1.0.0" "@nomicfoundation/hardhat-chai-matchers@^1.0.0" "@nomiclabs/hardhat-ethers@^2.0.0" "@nomiclabs/hardhat-etherscan@^3.0.0" "@types/chai@^4.2.0" "@types/mocha@>=9.1.0" "@typechain/ethers-v5@^10.1.0" "@typechain/hardhat@^6.1.2" "chai@^4.2.0" "hardhat-gas-reporter@^1.0.8" "solidity-coverage@^0.8.1" "ts-node@>=8.0.0" "typechain@^8.1.0" "typescript@>=4.5.0"

```
3. The deployment script needs to use `Storage`
4. In the README the network is a required option, to deploy it on the vechain configured network

### CODE REVIEW

**Comment by MakisChristou** [comment]
We have updated the main branch with the appropriate [fixes](https://github.com/vechainfoundation/hardhat-plugin-sample-ethers/commit/821fc52c2251e7d387755086372be42f9b4e9072). It is now ported in Typescript an contains the correct npm packages.

**Comment by ifavo** [comment]
@MakisChristou the other issues still exist:

1. the project can not be cloned and run, installation of dependencies are required afterwards
2. it still deploys the `Lock` instead of the `Storage` contract
3. it also requires the `--network vechain` option at the deployment run

**Comment by MakisChristou** [comment]
I understand 2. and 3. But not 1. How does your PR address 1?

**Comment by ifavo** [comment]
Given that a solo node already runs and exists, my expectations for this project are:

1. git clone
2. yarn/npm install
3. run the deployment script
4. *success*

> I understand 2. and 3. But not 1. How does your PR address 1?

If you clone the project, you are required to install dependencies, thats what the run command tells you. Here is my experience:

```shell
$ yarn
…
✨  Done in 26.60s.

$ npx hardhat run scripts/deploy.ts --network vechain
Error HH14: Your Hardhat project uses typescript, but it's not installed.
Please run: npm install --save-dev typescript
For more info go to https://hardhat.org/HH14 or run Hardhat with --show-stack-traces

$ yarn add --dev typescript
…
✨  Done in 1.73s.

$ npx hardhat run scripts/deploy.ts  --network vechain
Error HH13: Your Hardhat project uses typescript, but ts-node is not installed.
Please run: npm install --save-dev ts-node
For more info go to https://hardhat.org/HH13 or run Hardhat with --show-stack-traces

$ yarn add --dev ts-node                              
…
✨  Done in 1.42s.

  npx hardhat run scripts/deploy.ts  --network vechain
Error HH801: Plugin @nomicfoundation/hardhat-toolbox requires the following dependencies to be installed: @nomicfoundation/hardhat-network-helpers, @nomicfoundation/hardhat-chai-matchers, @nomiclabs/hardhat-ethers, @nomiclabs/hardhat-etherscan, @types/mocha, @typechain/ethers-v5, @typechain/hardhat, hardhat-gas-reporter, solidity-coverage, typechain.
Please run: npm install --save-dev "@nomicfoundation/hardhat-network-helpers@^1.0.0" "@nomicfoundation/hardhat-chai-matchers@^1.0.0" "@nomiclabs/hardhat-ethers@^2.0.0" "@nomiclabs/hardhat-etherscan@^3.0.0" "@types/mocha@>=9.1.0" "@typechain/ethers-v5@^10.1.0" "@typechain/hardhat@^6.1.2" "hardhat-gas-reporter@^1.0.8" "solidity-coverage@^0.8.1" "typechain@^8.1.0"

For more info go to https://hardhat.org/HH801 or run Hardhat with --show-stack-traces
```

Doing these installs and adding them to the package.json will remove uneccessary hurdles from the users journey to the first deployment.

**Comment by MakisChristou** [comment]
I have updated the deployment script to deploy the `Storage.sol` contract instead of `Lock.sol`. Right now if I do the following:

1. Clone repository
2. `npm install`
3. `npx hardhat run scripts/deploy.ts --network vechain`

It all works as expected.

**Comment by ifavo** [comment]
> 

@MakisChristou may I suggest to also use `Storage`  as variable name in the deploy script, it still is named `Lock`.

Additionally the package.json is still missing the dependencies, I run into the exact same experience as before. You might have a different one because you have the modules installed globally.

I suggest to also add the `--network vechain` option to the README, to make it easier for someone to get started and not look it up themself.

**Comment by MakisChristou** [comment]
I think all the requested changes have been merged. Closing this for now

**Comment by ifavo** [comment]
> I think all the requested changes have been merged. Closing this for now

Thank you. And while it is not relevant to the functionality, it reflects on the quality, having the variable names in the deployment script reflect the actual Storage contract and not the original Lock contract. It also ensures that users will understand the snippet better.

**Comment by ifavo** [comment]
I have just tested it by doing a git clone, yarn install and `npx hardhat run scripts/deploy.ts --network vechain`

it seems to miss one dependency:

```shell
$ npx hardhat run scripts/deploy.ts --network vechain

Error HH801: Plugin @nomiclabs/hardhat-truffle5 requires the following dependencies to be installed: @nomiclabs/hardhat-web3.
Please run: npm install --save-dev "@nomiclabs/hardhat-web3@^2.0.0"
```

after adding it, it worked instantly:

```shell
$ yarn add --dev @nomiclabs/hardhat-web3
…
✨  Done in 3.62s.

$ npx hardhat run scripts/deploy.ts --network vechain
Compiled 1 Solidity file successfully
Storage deployed to 0xb1747E3fA25022b0CFA5d2d90F1285D28Fbe8a24
```

**Comment by MakisChristou** [comment]
What about now?

**Comment by ifavo** [comment]
> ```shell
>  npx hardhat run scripts/deploy.ts --network vechain
> ```

**now** it works out of the box 🥳 

_P.S.: I still recommend https://github.com/vechainfoundation/hardhat-plugin-sample-ethers/pull/1#issuecomment-1506444179_

**Pull request closed without merging**
